apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: csr
  labels:
    app: redis
spec:
  serviceName: redis
  replicas: 6
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: docker.io/redis:5.0.6-alpine
        command:
          - "redis-server"
        args:
          - "/etc/redis/redis.conf"
          - --cluster-announce-ip
          - "$(MY_POD_IP)"
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: redis
          containerPort: 6379
        - name: cluster
          containerPort: 16379
        volumeMounts:
        - name: redis-conf
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /var/lib/redis
      volumes:
      - name: "redis-conf"
        configMap:
          name: "redis-conf"
          items:
            - key: "redis.conf"
              path: "redis.conf"
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: csr-storage
      resources:
        requests:
          storage: 200m