apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-job
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name: redis-cluster-job
    spec:
      initContainers:
      - name: init-redis
        image: busybox:1.27.2
        command: ['sh', '-c', 'until nslookup redis-5.redis.csr.svc.cluster.local; do echo waiting for redis; sleep 5; done;']
      containers:
      - name: redis
        image: redis:6.0.1-alpine
        command:
        - sh
        - -c
        - |
          echo "yes" | redis-cli -a 'cathaylife' --cluster create --cluster-replicas 1 \
          `echo $(getent hosts redis-0.redis.csr.svc.cluster.local | cut -d' ' -f1)`:6379 \
          `echo $(getent hosts redis-1.redis.csr.svc.cluster.local | cut -d' ' -f1)`:6379 \
          `echo $(getent hosts redis-2.redis.csr.svc.cluster.local | cut -d' ' -f1)`:6379 \
          `echo $(getent hosts redis-3.redis.csr.svc.cluster.local | cut -d' ' -f1)`:6379 \
          `echo $(getent hosts redis-4.redis.csr.svc.cluster.local | cut -d' ' -f1)`:6379 \
          `echo $(getent hosts redis-5.redis.csr.svc.cluster.local | cut -d' ' -f1)`:6379
      restartPolicy: Never
