apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-commander
  labels:
    app: redis-commander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-commander
  template:
    metadata:
      labels:
        app: redis-commander
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: rediscommander/redis-commander:latest
        ports:
        - name: redis-commander
          containerPort: 8081
        env:
        - name: REDIS_HOSTS
          value: redis:redis-access-service.csr.svc.cluster.local:6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-commander
  labels:
    app: redis-commander
spec:
  type: NodePort
  ports:
  - name: redis-commander
    protocol: "TCP"
    port: 8081
    targetPort: 8081
  selector:
    app: redis-commander