apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: csr
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    name: redis
  - port: 16379
    name: cluster
  selector:
    app: redis
  clusterIP: None