apiVersion: apps/v1
kind: Deployment
metadata:
  name: qpweb
  namespace: csr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qpweb
  template:
    metadata:
      labels:
        app: qpweb
    spec:
      containers:
      - name: qpweb
        image: hub.cathay/qpweb:1.0
        ports:
        - containerPort: 8080
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: qpweb
  namespace: csr
spec:
  selector:
    app: qpweb
  ports:
  - name: web
    port: 8080
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: qpweb
  namespace: csr
spec:
  hosts:
  - "qpweb.192.168.99.100.nip.io"
  gateways:
  - istio-system/istio-gateway
  http:
  - route:
    - destination:
        host: qpweb.csr.svc.cluster.local
        port:
          number: 8080
