apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: csr
  metadata:
    labels:
      app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
          - containerPort: 6379
            name: redis
          - containerPort: 16379
            name: cluster
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: csr
  metadata:
    labels:
      app: redis
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: cluster
    port: 16379
    targetPort: 16379