apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-configmap
data:
  .filebrowser.json: |
    {
      "port": 80,
      "baseURL": "/filebrowser",
      "address": "",
      "log": "stdout",
      "database": "/database.db",
      "scope": "/data"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  labels:
    app: filebrowser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser:v2.1.0
        ports:
        - name: web
          containerPort: 80
        volumeMounts:
        - name: filebrowser-json
          mountPath: /.filebrowser.json
          subPath: .filebrowser.json
        - name: data
          mountPath: /data
      volumes:
      - name: filebrowser-json
        configMap:
          name: filebrowser-configmap
          items:
          - key: .filebrowser.json
            path: .filebrowser.json
      - name: data
        hostPath:
          path: /zookeeper/amweb-log
      nodeSelector:
        kubernetes.io/hostname: cxl92008k8st03
---
apiVersion: v1
kind: Service
metadata:
  name: filebrowser
spec:
  selector:
    app: filebrowser
  ports:
  - name: web
    port: 8888
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: filebrowser
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/app-root: /filebrowser
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    traefik.frontend.passHostHeader: "true"
spec:
  rules:
  - http:
      paths:
      - path: /filebrowser
        backend:
          serviceName: filebrowser
          servicePort: 8888
