apiVersion: v1
kind: Service
metadata:
  name: amweb
spec:
  selector:
    app: amweb
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  - name: jmx-exporter
    port: 9105
    targetPort: 9105