kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-provisioner
  namespace: csr
  labels:
    app: nfs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      serviceAccountName: nfs-provisioner
      containers:
        - name: nfs-provisioner
          image: hub.cathay/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-provisioner
            - name: NFS_SERVER
              value: 10.97.42.86
            - name: NFS_PATH
              value: /zookeeper/nfs
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.97.42.86
            path: /zookeeper/nfs