apiVersion: apps/v1
kind: Deployment
metadata:
  name: amweb
  namespace: csr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: amweb
  template:
    metadata:
      labels:
        app: amweb
    spec:
      initContainers:
      - name: init-redis
        image: redis:5.0.6-alpine
        command:
        - sh
        - -c
        - |
          COUNT=$(redis-cli -h redis-0.redis.csr.svc.cluster.local cluster nodes | wc -l)
          until $COUNT -eq 6; do echo waiting for redis; sleep 2; done;
        command: ['sh', '-c', 'until nslookup redis-5.redis.csr.svc.cluster.local; do echo waiting for redis; sleep 2; done;']
      containers:
      - name: amweb
        image: hub.cathay/amweb:1.0
        ports:
        - containerPort: 8080
          name: web
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: amweb
  namespace: csr
spec:
  selector:
    app: amweb
  ports:
  - name: web
    port: 8080
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: amweb
  namespace: csr
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-gateway
  http:
  - match:
    - uri:
        prefix: "/AMWeb/"
    rewrite:
      uri: "/AMWeb/"
    route:
    - destination:
        host: amweb.csr.svc.cluster.local
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
 name: "amweb"
 namespace: "csr"
spec:
 host: "amweb.csr.svc.cluster.local"
 trafficPolicy:
   tls:
     mode: DISABLE