# Default values for amweb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: image-registry.openshift-image-registry.svc:5000/ebafweb/amweb:1.0.0-TEST-20201021.100401-996-addb8538771
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1536Mi