---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis-master
spec:
  ports:
  - name: redis-port
    port: 6379
  - name: redis-sentinel-port
    port: 26379
  selector:
    app: redis-master

---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave
  labels:
    app: redis-slave
spec:
  ports:
  - name: redis-port
    port: 6379
  - name: redis-sentinel-port
    port: 26379
  selector:
    app: redis-slave