---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis
        image: redis:6.0.1-alpine
        command:
          - "redis-server"
        args:
          - "--slave-announce-ip"
          - "$(POD_IP)"
          - "--replicaof"
          - "redis-master"
          - "6379"
        imagePullPolicy: IfNotPresent
        ports:
        - name: redis
          containerPort: 6379
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "redis-cli -h $(hostname) ping"
          initialDelaySeconds: 1
          timeoutSeconds: 5
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      - name: redis-sentinel
        image: hub.cathay/redis:6.0.1-alpine-sentinel
        imagePullPolicy: IfNotPresent
        env:
        - name: SENTINEL_DOWN_AFTER
          value: "1000"
        - name: SENTINEL_FAILOVER
          value: "5000"
        - name: SENTINEL_QUORUM
          value: "1"
        - name: SENTINEL_PORT
          value: "26379"
        - name: REDIS_MASTER
          value: "redis-master"
        ports:
        - name: redis-sentinel
          containerPort: 26379
      imagePullSecrets:
      - name: regcred