---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
spec:
  serviceName: "redis-sentinel"
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: redis-sentinel
        image: 10.95.33.59:5000/library/redis-sentinel:1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SENTINEL_DOWN_AFTER
          value: "500"
        - name: SENTINEL_FAILOVER
          value: "5000"
        - name: SENTINEL_QUORUM
          value: "2"
        - name: SENTINEL_PORT
          value: "26379"
        - name: REDIS_MASTER
          value: "redis-master"
        ports:
        - name: redis-sentinel
          containerPort: 26379
        volumeMounts:
        - name: "redis-conf"
          mountPath: /etc/redis
      imagePullSecrets:
      - name: regcred
  volumeClaimTemplates:
  - metadata:
      name: redis-conf
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ebafweb-storage
      resources:
        requests:
          storage: 1M
