---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-conf-redis-sentinel-0
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: redis-conf-redis-sentinel-0
    namespace: ebafweb
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: cxlsvr69
    path: /MICROCSR/test/redis-conf-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-conf-redis-sentinel-1
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: redis-conf-redis-sentinel-1
    namespace: ebafweb
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: cxlsvr69
    path: /MICROCSR/test/redis-conf-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-conf-redis-sentinel-2
spec:
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: redis-conf-redis-sentinel-2
    namespace: ebafweb
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: cxlsvr69
    path: /MICROCSR/test/redis-conf-2