---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-standalone-exporter
  labels:
    app: redis-standalone-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-standalone-exporter
  template:
    metadata:
      labels:
        app: redis-standalone-exporter
    spec:
      containers:
      - name: redis-exporter
        image: oliver006/redis_exporter:alpine
        imagePullPolicy: IfNotPresent
        args:
          - "--redis.addr"
          - "redis://redis-standalone.ebafweb.svc.cluster.local:6379"
        ports:
        - name: redis-exporter
          containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-standalone-exporter
  labels:
    app: redis-standalone-exporter
spec:
  ports:
  - name: redis-exporter
    port: 9121
  selector:
    app: redis-standalone-exporter