---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-sentinel
  labels:
    app: redis-sentinel
spec:
  serviceName: "redis-sentinel"
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
      - name: redis-sentinel
        image: 10.95.28.159:8083/baseimage/redis:6.0-sentinel-1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: SENTINEL_DOWN_AFTER
          value: "500"
        - name: SENTINEL_QUORUM
          value: "2"
        - name: REDIS_MASTER
          value: "redis-master"
        - name: REDIS_SLAVE
          value: "redis-slave"
        ports:
        - name: redis-sentinel
          containerPort: 26379
